Pass values to the function using HTTP headers / EnvVar
fnproject/hotwrap pull request #5
Opened 2019-02-04 12:51 UTC by delabassee

Example: `curl -H "abc:123" -H "xyz:456" http://localhost:8080/t/app/func` will set the `FN_HEADER_Abc=123` and `FN_HEADER_Xyz=456` EnvVar in the function container.

This is needed for one of the Flow102 example.

2019-02-05 16:14 UTC, denismakogon requested changes

2019-02-05 16:14 UTC, denismakogon commented on hotwrap.go
> +	hdr := fctx.Header()
you'd need to try to check whether you can create HTTP context, if you can do that you'd need to take headers from http context, if not - take headers from invoke context.

2019-02-05 16:14 UTC, denismakogon commented on hotwrap.go
> +			funcEnv = append(funcEnv, envVar)
it's not necessary, see my comment above.

2019-02-11 09:09 UTC, zootalures commented
I'm going to close this in favour of a (I think) slightly simpler version of this  in #6  @delabassee  could you take a look at that one and see what you think?

2019-02-11 09:09 UTC, closed without merging